name: Build Resume

on:
  push:
    paths:
      - "public/resume/resume.tex"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-full

      - name: Build resume PDF
        working-directory: ./public/resume
        run: pdflatex resume.tex

      - name: Upload built PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume-pdf
          path: public/resume/*.pdf

      - name: Commit resume.pdf back to repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add public/resume/*.pdf
          git commit -m "Auto-build resume PDF"
          git push
